# Generated by Django 6.0.7 on 2026-07-25 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_childcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubChildCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_child_category_name', models.CharField(max_length=100)),
                ('child_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.childcategory')),
            ],
        ),
    ]
