# Generated by Django 6.0.7 on 2026-07-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_clothes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='gender',
            field=models.CharField(default='Men', max_length=10),
        ),
        migrations.AddField(
            model_name='clothes',
            name='type',
            field=models.CharField(default='Upper', max_length=10),
        ),
    ]
