# Generated by Django 6.0.7 on 2026-07-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_clothes_gender_clothes_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='child',
        ),
        migrations.RemoveField(
            model_name='subchildcategory',
            name='child_category',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='subchild',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ChildCategory',
        ),
        migrations.DeleteModel(
            name='ParentCategory',
        ),
        migrations.DeleteModel(
            name='SubChildCategory',
        ),
    ]
