# Generated by Django 6.0.7 on 2026-07-31 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_cart_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.FileField(upload_to='product/'),
        ),
    ]
